[package]
name = "actix-codec-p"
version = "0.3.0"
edition = "2021"

[dependencies]
bitflags = "1.3"
bytes = "0.5"
futures = "0.3"
pin-project = "1.0"
tokio = { version = "0.2", features = ["io-util"] }
